### ISSUE TITLE
tsl/torch_geometric_temporal

### ISSUE THREAD

**Issue by BANLANGEN11** [gravins/TG-ODE#1]
Thank you very much for your contribution!Where are files tsl and torch_geometric_temporal?
![1111111111111](https://github.com/gravins/TG-ODE/assets/71771687/1f181ebc-8b95-4715-8a64-dcaecb5bec8b)

**Comment by gravins** [comment]
Hi, 
thanks for your query.

[tsl](https://torch-spatiotemporal.readthedocs.io/en/latest/) and [torch_geometric_temporal](https://pytorch-geometric-temporal.readthedocs.io/en/latest/index.html) are two python libraries that you can install via PIP or Conda. 

I recommend installing them following the versions in the [env.yml](https://github.com/gravins/TG-ODE/blob/main/env.yml) file, i.e., `torch-spatiotemporal==0.9.0` and `torch-geometric-temporal==0.54.0`
